### ISSUE TITLE
Allow screen to be pinned to prevent babies closing the app

### ISSUE THREAD

**Issue by pserwylo** [babydots/babyphone#5]
The [Baby Dots](https://github.com/babydots/babydots) allows the screen to be locked, in which case the baby using the phone cannot accidentally close the app and cause damage elsewhere on the device.

I propose this is done by forcing them to tap the hang up button multiple times in succession, with appropriate prompts to any adult using the app so they know to do this.

**Comment by yamatt** [comment]
The pin feature in Android has it's own mechanism to escape by pressing back and switch buttons (either side of the home button) at the same time.

I recommend relying on that first.

**Comment by pserwylo** [comment]
Welcome, and thanks for being the first person to comment on my little project here :)

Yes, the approach put in play definitely still allows for using the default mechanism supported by Android. My experience experimenting with the Baby Dots app was that although it works just fine, the user experience can be clunky and hard to use/remember. Even though Android reminds you of exactly how to escape with a prompt each time you enter screen pinning mode - my experience watching users is that they don't read this, click "ok", and then have no way how to exit this sticky mode.

F-Droid has built a new version to be deployed in the next couple of days. Please feel free to let me know once it is released as to whether it works well enough for you and your little one.

**Comment by pserwylo** [comment]
Funny you should mention that. There is a [good discussion on the PianOli tracker](https://github.com/nicolasbrailo/PianOli/issues/12) about how easy or hard it is to unlock.

For this reason, in order to implement unlocking in this app, I've taken the code from BabyDots, extracted the functionality for unlocking into something that I can publish as a separate library. My hope is that it will allow easy configuration where parents can choose an unlock mechanism that works for them and their baby and switch easily if one becomes too easily to unlock. Hopefully we can build a little array of user friendly but baby-safe ways to lock the app that works for both BabyDots, BabyPhone, and perhaps even other apps such as PianOli.

**Comment by pserwylo** [comment]
Closing as complete. For some time we've had this featuer now. I've also extracted the code into a common library [babydots/immersivelock](https://github.com/babydots/immersivelock) whcih is now shared by BabyDots, BabyBook, and this repo.
